---
title: "心理学統計法3日目"
---

# 準備
```{r}
# データ整形汎用パッケージ
library(tidyverse)
# データ要約・可視化パッケージ
library(summarytools)
# 描画の際に文字化けするMacユーザは次の行のコメントアウトをとって実行する
old = theme_set(theme_gray(base_family = "HiraKakuProN-W3"))
```

# 分散分析をやってくれるソフトをネッットから

```{r}
source('http://riseki.php.xdomain.jp/index.php?plugin=attach&refer=ANOVA君&openfile=anovakun_482.txt',encoding = 'CP932')
```


# 一要因3水準群間計画(Between Design)
```{r}
groupA <- c(3,4,4,3)
groupB <- c(7,8,9,6)
groupC <- c(5,4,6,7)
BD1 <- data.frame(groupA,groupB,groupC) %>%
        tidyr::gather(key,dat)
anovakun(BD1,'As',3)
```

# 一要因3水準群内計画(Within Design)
```{r}
id1 <- c(10,5,9)
id2 <- c(9,4,5)
id3 <- c(4,2,3)
id4 <- c(7,3,5)
WD1 <- data.frame(rbind(id1,id2,id3,id4)) 
anovakun(WD1,'sA',3,peta=TRUE)
```

# 二要因2*3水準群間計画(Between Design)
```{r}
dat <-  data.frame(A=rep(1:2,each=15),
                   B=c(rep(1:3,each=5),rep(1:3,each=5)),
                   val=c( 6, 4, 5, 3, 2,
                        10, 8,10, 8, 9,
                        11,12,12,10,10,
                          5, 4, 2, 2, 2,
                          7, 6, 5, 4, 3,
                        12, 8, 5, 6, 4) )
anovakun(dat,'ABs',2,3)

```

# 二要因2*3水準群内計画(Within Design)
## 数字は同じだけどデザインが違うことに注意！
```{r}
dat <-  data.frame(A=rep(1:2,each=15),
                   B=c(rep(1:3,each=5),rep(1:3,each=5)),
                   val=c( 6, 4, 5, 3, 2,
                        10, 8,10, 8, 9,
                        11,12,12,10,10,
                          5, 4, 2, 2, 2,
                          7, 6, 5, 4, 3,
                        12, 8, 5, 6, 4) )
dat$ID <- rep(1:5,6)
dat

# 列の並べ替え(anovakunは左端がID,右端が値)
dat2 <- dat %>% dplyr::select(ID,A,B,val)

anovakun(dat2,'sAB',2,3,long=T)
```

# 二要因2*3混合計画(Mixed Design)
## データは同じだけどデザイン指定が違うことに注意！
```{r}
anovakun(dat2,'AsB',2,3,long=T)
```

